### ISSUE TITLE
Update namespace for consistency w/ other plugins

### ISSUE THREAD

**Issue by TheAlmightyBob** [TheAlmightyBob/Calendars#11]
Other Xamarin plugins have switched from "X.Plugin" to "Plugin.X", so that all the available plugins for an app are grouped together for easy browsing/searching.

Described near the bottom of this post, "Unified Namespaces":
http://motzcod.es/post/134355371052/build-apps-faster-with-plugins-for-xamarin

**Comment by jamesmontemagno** [comment]
Yay!!!! :)

**Comment by jamesmontemagno** [comment]
https://github.com/TheAlmightyBob/Calendars/pull/12  implemeneted
