### ISSUE TITLE
Android all-day events have incorrect times

### ISSUE THREAD

**Issue by TheAlmightyBob** [TheAlmightyBob/Calendars#18]
An event that is created as "all-day" via the Google Calendar app is returned by the Calendars API as running from 5pm the previous day to 5pm on the intended day. (the "all-day" flag is still correctly set, however)

Meanwhile, an event that is created via the Calendars API as "all-day" with start/end times of midnight on the target/next days may be confusingly displayed by the Calendar app as being one or two days depending on the screen. (haven't tried 3rd-party calendars)

This sneaky bit hidden deep in the Android docs is the likely culprit:
"If allDay is set to 1 eventTimezone must be TIMEZONE_UTC and the time must correspond to a midnight boundary"

**Comment by TheAlmightyBob** [comment]
a0c56d3 improved things significantly, but this is not completely fixed.

All-day events created on Android via the Calendars API appear to span two days in some calendar apps (including the Google Calendar app).
However, the event details views of these apps always shows the correct time (just the one day), it is only the grid-style views that display them as two-day events.
We are configuring the events exactly as specified in the Android docs, and inspecting the values in the database shows our events as _identical_ to those created via Google Calendar (other than the fields specifying the app that created the event, of course).

I really don't know what could be different...

**Comment by Yogeshk25** [comment]
Is this issue already fixed?
Release Note of Nuget store for "0.6.0-beta" says it's fixed.
If fixed please close this issue.

**Comment by TheAlmightyBob** [comment]
It is not fixed. The release note, "Android all-day events are no longer affected by timezone," refers to my previous comment on this issue, "a0c56d3 improved things significantly, but this is not completely fixed."

The "help wanted" tag on this issue is also still quite accurate.

This is the main issue that has been blocking a 1.0 release.

**Comment by trevoriancox** [comment]
Just chiming in to say this is still a real Android issue; I'm seeing this on an Android 7.0 ASUS tablet. I tried specifying other times of day for the start time but it doesn't help. Not specifying AllDay is not an option; it will show the times even if midnight-midnight, which would look odd.

**Comment by TheAlmightyBob** [comment]
@trevoriancox If you happen to still be using this library and seeing this issue, I encourage you to check out version 0.7.7-beta.
