### ISSUE TITLE
External ID for calendar on Android seems wrong

### ISSUE THREAD

**Issue by Crojach** [TheAlmightyBob/Calendars#23]
I have started using the package on iOS and Android and came across a strange error.

I have created a new calendar on my Google Account, lets call it MyAmazingCalendar and when I call the CrossCalendar.Current.GetCaledarsAsync() function on iOS I get the calendar and its External ID which looks to be of type GUID.

On Android, however, the External ID, is in my case 7 which is just its index in the list of calendars.

This causes problems when I add events to this calendar. When adding from iOS the entry is visible on calendar.google.com where, when added from an Android device, it's only visible on that device.

Any ideas? I am using the 0.6.10 version.

**Comment by TheAlmightyBob** [comment]
Hi,

The external ID is normal. iOS and Android just use different types of identifiers (Windows, too, is different from either).

I'm not sure why your added entries are not syncing. I just tried adding an entry on my own Google calendar via the test app (https://github.com/TheAlmightyBob/CalendarsTester), and it appeared pretty quickly on other devices.

If you add an entry to that same calendar via a different calendar app (such as whatever the default one is on your particular phone), it is visible from other devices?

I will note that this plugin does not communicate directly with cloud calendars, only local device calendars. Any interaction with the cloud version depends on the device's calendar synchronization.
