### ISSUE TITLE
Crash on iOS 10

### ISSUE THREAD

**Issue by bmacombe** [TheAlmightyBob/Calendars#24]
When trying to access calendars on iOS 10 the app hard crashes, no exception.  Loaded an iOS 9 emulator and it works fine.  Same code works on Android fine also

I'm downloading the source to attempt to troubleshoot.

**Comment by bmacombe** [comment]
Just tried running the iOS test app, it crashes as soon as you click run everything

**Comment by bmacombe** [comment]
Crashes at line 462 in CalendersImplentations when calling
var accessResult = await _eventStore.RequestAccessAsync(EKEntityType.Event).ConfigureAwait(false);

**Comment by bmacombe** [comment]
Looks like a change in iOS 10 that requires a new key added the info.plist

https://developer.apple.com/library/prerelease/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW15

Adding below fixed the issue.  Maybe consider updating the read me iOS instructions with this new requirement?  Thanks!

<key>NSCalendarsUsageDescription</key>
  <string>Test</string>

**Comment by andnes-cap** [comment]
This fix works perfectly. Thank you!

**Comment by bmacombe** [comment]
Great!  Thank you for making this project, it was very helpful and easy to use!

**Comment by andnes-cap** [comment]
I'm not the author, just someone who struggled with the same error as you ;) but I agree, great project!

**Comment by bmacombe** [comment]
Lol, sorry...first time really using Github to do more than browse source for a problem...read the UI wrong!
