### ISSUE TITLE
Plugin.Calendars.Abstractions.PlatformException: The calendar is read only. ---> Foundation.NSErrorException: Exception of type 'Foundation.NSErrorException' was thrown.

### ISSUE THREAD

**Issue by jamal-deen** [TheAlmightyBob/Calendars#30]
I have added the  [NuGet plugin](https://www.nuget.org/packages/CClarke.Plugin.Calendars/0.6.10-beta) into my Xamrin Forms project. I could add the events into my `Android` default google `calendar` mobile app, but when I run the same code into `iOS` project it is showing the below exception in `Plugin.Calendars.Abstractions.PlatformException: The calendar is read only. ---> Foundation.NSErrorException: Exception of type 'Foundation.NSErrorException' was thrown.`
in these lines.
	
```
var calendars = await CrossCalendars.Current.GetCalendarsAsync();
				if (calendars.Count > 0)
					await CrossCalendars.Current.AddOrUpdateEventAsync(calendars[0], _event);

```

**Comment by TheAlmightyBob** [comment]
This is most likely a difference in the calendars you are using, not a difference in platforms. You can check the CanEditEvents property of the calendar before calling AddOrUpdateEventsAsync on it. 

Simply adding to the first calendar in the list of calendars is probably not what you want...
