### ISSUE TITLE
Unable to make diffrent background color and clickable of special Dates

### ISSUE THREAD

**Issue by NazarAbbas** [TheAlmightyBob/Calendars#32]
Hi, We are unable to  make  different background color  and clickable for  special dates, please let we know how can do that.

Thanks

**Comment by TheAlmightyBob** [comment]
I'm sorry, I don't understand the question...? This is not a UI component...

If you're wishing to change the color of a specific event separately from the calendar color, then I don't believe that is possible on iOS or Windows.
