### ISSUE TITLE
Calendar Color

### ISSUE THREAD

**Issue by Toemsel** [TheAlmightyBob/Calendars#38]
I checked your code which format the color has to be. (Documentation should be more clear about that) However, it seems to work on iOS but not on Android.

`public const string CALENDAR_COLOR = "#F09500";
await CrossCalendars.Current.CreateCalendarAsync(CALENDAR_NAME, CALENDAR_COLOR);`

Results in a iOS Calendar with exactly that color. But with a black color on Android.

Thanks for your time.

**Comment by TheAlmightyBob** [comment]
How are you verifying the resulting color on Android?

If I test this with my CalendarsTester Xamarin.Forms project, it does indeed show black on Android, as it's trying to render that as #00F09500 (i.e. argb with a missing alpha..).

However, the Google Calendar app shows the expected color.

**Comment by Toemsel** [comment]
Ah, I do have to include the alpha channel. Ok, I will try that out.
I test it with the default Calendar app on the emulator.

**Comment by TheAlmightyBob** [comment]
Hm. I was also using the default Calndar app on the emulator. Which Android version were you testing?

I had noticed this issue in CalendarsTester before but figured it was just a problem with that app since the Android Calendar seemed to just ignore the alpha value in my testing.

**Comment by Toemsel** [comment]
API 23 VS Emulator. Compile: Target 7.1 and min version 4.2.

**Comment by TheAlmightyBob** [comment]
Strange. Just tried the API 23 VS Emulator and the color still displayed as expected.
