### ISSUE TITLE
Exception : Editing recurring events is not supported

### ISSUE THREAD

**Issue by bo3po** [TheAlmightyBob/Calendars#42]
Hi,

I'm using the latest Nuget. On iOS this works perfect. On Android I ran into trouble. I'm not updating an exsisting event -I'm creating a new event. But I get this error: Editing recurring events is not supported. I think I might hit line 364 in Calendars.Plugin.Android/CalendarsImplementation.cs. I have no idea why. Is this a bug or am I using it wrong? The IsEventRecurring-method is refereing to a DURATION that I have no control over.

I'm on a Nexus 5x.

Please help :)

**Comment by TheAlmightyBob** [comment]
Are you by chance setting the `ExternalID` property on the `CalendarEvent` object that you pass to `AddOrUpdateEventAsync`? That should be left empty if you're creating a new event.

**Comment by bo3po** [comment]
Yes I was. I was setting the ExternalID. On iOS it worked with the ExternalID. On Android it did not like me adding an event. But removing the ExternalID from my code made it work on both platforms.

Thank you VERY much. Works perfect now.

**Comment by TheAlmightyBob** [comment]
Not positive, but _most likely_ the ExternalID you provided to iOS did not match any existing events so it just ignored it, whereas the one you provided to Android clearly matched an existing recurring event.

**Comment by bo3po** [comment]
Perhaps. It works fine. I create events (and ever edit). At most I delete them. I think I have mistaken the ExternalID for a calendar id. Might have. Great work...
