### ISSUE TITLE
Add .NETStandard support for NuGet package

### ISSUE THREAD

**Issue by coldacid** [TheAlmightyBob/Calendars#44]
Using this plugin with a .NETStandard Forms project results in a warning that the package "may not be fully compatible with [the] project" as it is restored using .NETFramework,Version=v4.6.1. The CClarke.Plugin.Calendars NuGet package should be updated to work properly with .NETStandard projects.

**Comment by TheAlmightyBob** [comment]
Interesting, thanks for reporting. I hadn't thought it was a problem for NETStandard projects to use PCLs.

**Comment by coldacid** [comment]
They can be referenced so long as `PackageTargetFallback`/`AssetTargetFallback` property in the NETStandard project file includes a target that the PCL can support, but the resulting library is only guaranteed to work on that fallback platform and will die anywhere else. The ability to use a PCL library from a NETStandard one is only intended as a temporary measure anyway.

**Comment by TheAlmightyBob** [comment]
@coldacid 0.6.45-beta should be more .NETStandard-friendly

**Comment by TheAlmightyBob** [comment]
@jphellemons What platform are you seeing this on? I was able to repro with UWP, but Android/iOS were fine.

**Comment by jphellemons** [comment]
It's UWP. Win 10 build 16299.371 fall creator update. Since Android and iOS require me to have physical devices or an emulator which is slow, so I mainly test/dev for uwp atm.

**Comment by TheAlmightyBob** [comment]
@jphellemons Okay, I think UWP support is simply broken right now. Would you mind creating a new issue?


(the Android emulator is a lot faster than it used to be... but yeah it's still not going to compete with UWP)
