### ISSUE TITLE
Can't find the plugin after installation

### ISSUE THREAD

**Issue by elusiven** [TheAlmightyBob/Calendars#47]
I downloaded the plugin via nuget and installed it to all platforms and pcl. Can't find the reference to it just as if it wasn't installed but it is.. Any ideas?

**Comment by TheAlmightyBob** [comment]
I'm not sure, sorry. Are you seeing that your packages.config file got updated but your .csproj files didn't? I've seen that before with another package that I use in one of my own apps, after it was updated to .NET Standard, however I tested the .NET Standard version of this package with multiple PCL-based apps without trouble. But you could try specifying the previous version (0.6.33-beta) to see if that makes any difference?

Also, are you missing the reference in all projects, or just certain projects (e.g. PCL vs. platform-specific)?

If you figure out the problem, please let me know.

**Comment by Im-PJ** [comment]
I'm seeing the same issue in my .NET standard project however I can find reference in platform specific projects. Any help?

**Comment by TheAlmightyBob** [comment]
@Im-PJ Sorry I would need much more information about your project and what issue you're seeing.
