### ISSUE TITLE
Filter on events created by the calling app

### ISSUE THREAD

**Issue by TheAlmightyBob** [TheAlmightyBob/Calendars#6]
Trying to capture the request/discussion from issue #3, as it's a bit out of the scope of that issue.

The request is to "easily filter all events that were created by my app in order to update or delete them."

Thoughts:

1. Is creating a calendar for the app insufficient?
  * depending on platform, the app may be able to write to "shared" calendars, or the user may be able to add events to the app's calendar...

2. Can we leverage platform-specific features for this? Android has some built-in fields to track the "owner" (which we automatically set to the app's ID, but don't otherwise expose)... Windows has something similar at the calendar level, but I'm not sure about the event level... and I can't think of anything like this on iOS at the moment...
3. ...Or do we need to add our own custom field? Is *that* feasible cross-platform, or would we want a mix of 2 and 3?

**Comment by TheAlmightyBob** [comment]
It should be noted that the current workaround for this is to just have the app separately store the IDs for the calendars/events it creates... via settings, Sqlite, cloud, twitter, whatever.

**Comment by TheAlmightyBob** [comment]
Closing because it's non-trivial to implement and storing IDs in the app really seems the better way to go anyhow.

**Comment by nielscup** [comment]
Some help needed here: I am trying to use the externalID (iOS) to save the event, but when I set the external ID to a value, it is changed whenever I retrieve the events. How can I obtain the ID when saving an event? 

Also, if I would save the event IDs in my app, they can get out of sync with my calendar, for instance when I uninstall my app and later reinstall it.

**Comment by TheAlmightyBob** [comment]
AddOrUpdateEvent fills in the ExternalID property of the passed-in CalendarEvent object.
I admit that fact should probably be mentioned in the function description.

For the latter question, I don't have any helpful thoughts for you. My immediate thought is that if the user has chosen to uninstall the app, then those events don't belong to the app anymore. If you need to support installing the app onto a device that already has events you want to manage, you could support some kind of explicit user-driven import step.
