### ISSUE TITLE
Question: Check if events exist in calendar

### ISSUE THREAD

**Issue by AnthonyLatty** [TheAlmightyBob/Calendars#64]
I was wondering , does this plugin offers a way to check if a particular event already exists in the calendar?

**Comment by TheAlmightyBob** [comment]
`GetEventById`?

**Comment by AnthonyLatty** [comment]
Do you have a sample showing that method specifically? Im looking at the docs and im seeing that method `GetEventByIdAsync()` but it takes an ExternalID im not sure how this ID is populated.

**Comment by TheAlmightyBob** [comment]
That ID comes from the OS. So after you previously added the event via `AddOrUpdateEventAsync`, you would grab the `ExternalID` property from your `CalendarEvent` for later use. (this is described in the example section of the Readme, although it doesn't actually show the "later" code)

**Comment by AnthonyLatty** [comment]
Okay thanks, got it working :)
