### ISSUE TITLE
I get Permision error on android even though i have added those permissions

### ISSUE THREAD

**Issue by abrantie1z** [TheAlmightyBob/Calendars#65]
You specified in your read.me that we add the write calender and read calender permissions in android, i did yet anytime i run the codes to get calenders, i get permission error.

**Comment by TheAlmightyBob** [comment]
You still need to request the calendar permission from the user (and they need to grant it), using something like https://github.com/jamesmontemagno/PermissionsPlugin

**Comment by abrantie1z** [comment]
It worked like charm sir! Thank you for your quick reply .
