### ISSUE TITLE
Error while creating the events in IOS

### ISSUE THREAD

**Issue by sandeepmvn2019** [TheAlmightyBob/Calendars#66]
Error Message:-
No active calendar Sources available to create calendar on

**Comment by TheAlmightyBob** [comment]
@sandeepmvn2019 Do you already have existing calendars? If so, what kind? Can you add new calendars to their sources through the calendar app?

That message essentially means we tried every way we could to create the calendar but iOS wouldn't let us. This generally means there are no calendar sources on the device or they are all read-only (such as Gmail). It is odd that even falling back to the "local" source isn't working, but I suppose it's possible for that to be unavailable. Unfortunately I don't think there's anything the library can do for you in that situation.  I actually spoke to Apple's EventKit developers about this at WWDC this year, but they didn't really have ideas either.

**Comment by TheAlmightyBob** [comment]
@sandeepmvn2019 Are you seeing this be specific to iOS 13? I just noticed this error when testing on an iOS 13 simulator, but it still works fine on previous versions. Haven't had a chance to investigate yet.

**Comment by TheAlmightyBob** [comment]
Okay, the reason I was seeing this error in the unit tests was due to https://forums.developer.apple.com/thread/120850 ("[EventKit] Client tried to open too many connections to calaccessd. Refusing to open another"). I wouldn't expect that to affect you if you are using the library normally via the singleton interface (`CrossCalendars.Current`). The tests are special in that they reinitialize things for each test case and apparently iOS doesn't like that anymore.

**Comment by bo3po** [comment]
Great. Any workarounds/solutions for this? I'm using the singleton CrossCalendars.Current way.

**Comment by TheAlmightyBob** [comment]
@bo3po You've responded to two different issues, which I no longer think are related. Are you sure you're seeing this same error? Are you seeing "[EventKit] Client tried to open too many connections to calaccessd. Refusing to open another" in the log?

**Comment by bo3po** [comment]
hi. you are right. i thought they where related. sorry. i delete the issue?

**Comment by TheAlmightyBob** [comment]
@bo3po well not the issue but you can delete your comments here (and then I'll delete mine) to reduce confusion

**Comment by TheAlmightyBob** [comment]
Closing due to lack of response from OP.
