### ISSUE TITLE
Not working in iOS 13

### ISSUE THREAD

**Issue by bo3po** [TheAlmightyBob/Calendars#67]
Hi,

The create event in an existing calendar does not work. There is a boolean telling if the event was added and that returns false. I'm using NetStandard2.0 in a Xamarin Form.

Any workarounds maybee?

**Comment by TheAlmightyBob** [comment]
Can you be more specific? You're only seeing this on iOS 13? What boolean are you referring to? Are you getting an error?

I was able to repro #66 on iOS 13, but adding events to an existing calendar is still working for me.

**Comment by bo3po** [comment]
hi

thanks for getting back to me. i'm not sure this is an error after some
recomiling i did. i can in fact add it but not remove it. that is
probably something else. this was working fine aa week ago.

i'll remove the issue ok? thank you for your time.

regards,

bo
