### ISSUE TITLE
How get the default calendar

### ISSUE THREAD

**Issue by hed27m** [TheAlmightyBob/Calendars#75]
Hi! i am trying to add a event to my calendar default app on my android app but the documentation doesnt show how get the default calendar to add the event 

await CrossCalendars.Current.AddOrUpdateCalendarAsync( -- this is what i need to get --, calendarEvent);

 thank you!

**Comment by TheAlmightyBob** [comment]
Hi @hed27m,

Android does not have the concept of a default calendar like iOS does.

I personally would recommend letting the user choose which calendar to use.

The Xamarin Conference App, however, took an approach of "just use the first writeable calendar": https://github.com/xamarinhq/app-conference/blob/c379ccaf2c72c7c1005a03a5f7345aa9a2bdecd1/src/Conference.Clients.Portable/Services/ReminderService.cs#L204

**Comment by TheAlmightyBob** [comment]
(individual calendar applications may have implemented their own concepts of "default calendar," but that's app-specific)
