### ISSUE TITLE
Reminder is not working in Android 

### ISSUE THREAD

**Issue by PraveenPotla** [TheAlmightyBob/Calendars#77]
I am using the latest plugin date is added to a calendar is working fine but the reminder is not working
See below code I am using
![Screenshot_1](https://user-images.githubusercontent.com/43574666/82884583-888ff000-9f61-11ea-8b35-d735b32e106a.png)

**Comment by TheAlmightyBob** [comment]
@PPotlaACR What is the problem? Are you receiving an error? Does the event get created but no reminder is present?

I don't think I've ever tried creating a reminder with a negative `TimeBefore` value. Are you wanting it to fire 10 minutes after the event starts? I'm not certain if that's supported on all platforms...
