### ISSUE TITLE
[Question] Do you recommend setting UTC times?

### ISSUE THREAD

**Issue by jamesmontemagno** [TheAlmightyBob/Calendars#8]
Everything in my database is a UTC time, is it cool to pass that down?

**Comment by TheAlmightyBob** [comment]
I'm pretty confident that will work, although quite ashamed to realize I don't have unit tests for it. :(
Assuming it's specified in the Kind, of course.

And if you find it doesn't work properly, I would definitely consider that a bug!

**Comment by jamesmontemagno** [comment]
Hey there! Yup, I am specifying the Utc kind and it is working great! I have lots of small improvements that I will be making over the week as I make this a pretty core piece of an app I am working on :) tehehe
